use_frameworks!

platform :ios, '10.0'

target 'Z3LocationService_Example' do
  pod 'Z3LocationService', :path => '../'
  pod 'Z3DBService', :path => '../../Z3DBService'
  pod 'Z3Network', :path => '../../Z3Network'
  pod 'CoordinateTransform', :path => '../../CoordinateTransform'
end
